### ISSUE TITLE
Better instructions for html highlighting.

### ISSUE THREAD

**Issue by chigur** [isagalaev/highlight.js#1000]
While doing highlighting for `html` syntax I have found that specifying `class="xml"` produces better highlighting for `html`. Can this be documented somewhere?.

**Comment by chigur** [comment]
I just saw that the class applied for `html` highlighting on the demo [page](https://highlightjs.org/static/demo/) is also `xml`. I should have seen that first, my bad.

**Comment by isagalaev** [comment]
We have a single definition for all XML-like languages, HTML included. Because HTML is the most common one, the language even called "HTML, XML" on the demo page. Using "xml" and "html" as a class name is equivalent, and all such aliases are documented in [the reference](http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html).

**Comment by veccora** [comment]
Each time I add HTML code in between the pre and code tags I get no output at all. Maybe sometimes I get a few lines of text that is included in the code. But no div tags or etc...

Other code shows as it should, only HTML/XML are giving me issues.

**Comment by isagalaev** [comment]
@veccora you should escape `<` and `>` symbols with `&lt;` and `&gt;` if you want to see them on the page, it's how HTML works and it has nothing to do with highlight.js in particular.

(Also, please don't hijack other issues with random follow-up questions.)
