### ISSUE TITLE
Markdown: Highlight the code?

### ISSUE THREAD

**Issue by IngwiePhoenix** [isagalaev/highlight.js#1095]
When highlighting Markdown, I can see the backticks being recognized and colored differently. But when we already see that there is a language specified, why can't we try to highlight it, since we might as well have the correct bundle/languages loaded?

**Comment by isagalaev** [comment]
It can't be done with the current parser because the words it highlights have no meaning for it. The parser understands that it sees backticks and can understand that there's a word after those but currently it can't even remember this word to use later, let alone understand that it should be used as the key for a sub-language. Implementing something like this is actually a very major re-implementation of the core parser and the design is not obvious at all.

That said, I admit that I'm as prone to over-complicating things in my head as the next guy, so if anyone could come up with a good idea for an implementation, I'd be very interested to look at the code.
