### ISSUE TITLE
PHP degraded in 9.x?

### ISSUE THREAD

**Issue by Rarst** [isagalaev/highlight.js#1142]
I went to update my site from 8.4 to 9.3 and noticed that PHP highlight lost details. Seems to no longer recognize variables (maybe more?).

See screenshot before/after:

![highlight-js-php-comparison](https://cloud.githubusercontent.com/assets/737584/14406294/9a963958-feac-11e5-8a7d-8d994ccd3b6f.png)

Example, screenshot was taken from, live here http://www.rarst.net/code/dependency-injection/ (still on 8.4 hadn't pushed 9.3 up).

**Comment by isagalaev** [comment]
Dropping highlighting of regular variables was deliberate, this is a design decision. We should bring back `$this` though as it is special…

**Comment by isagalaev** [comment]
I've fixed `$this` and have gone ahead and fixed the whole issue, as it is unlikely we revert to highlighting plain user-defined variables.

**Comment by Rarst** [comment]
Why so?.. Variable seems to be pretty staple thing to highlight.

Loosely related — I also find it very nifty in IDE when variables and passed arguments are treated separately for highlight, easy to distinguish what is passed into function and what is created inside of it.

**Comment by isagalaev** [comment]
The reason is two-fold.

First, we just want to be consistent across languages. Most highlighters don't highlight local variables in other languages simply because they're not syntactically distinguishable. In PHP (and, say, Perl) they're easy to highlight because of the `$` sign. But "because we can" is not reason enough. 

Second, one of our design guidelines is to keep the bulk of code plain and only highlight things that are semantically significant, and highlighting them will add to code readability (all of this highly subjective and fuzzy, of course). Thus, we don't highlight many things that others do: `UPPERCASE_CONSTANTS`, `CamelCaseNames`, `.method_calls()`.

>  I also find it very nifty in IDE when variables and passed arguments are treated separately for highlight

This we can't do because a highlighter has to work at the syntactic level, it can't keep track of the meaning of identifiers, for example.

**Comment by Rarst** [comment]
Fair enough, thanks for the fix on `$this` at least. :)

**Comment by isagalaev** [comment]
You're welcome! :)

**Comment by Rarst** [comment]
Looked for something in older post and PHP highlight is nearly gone in some snippets.

![highlight-js-while](https://cloud.githubusercontent.com/assets/737584/15615134/33b003ae-2445-11e6-93d0-4bc9fa5c450f.png)

Without variables, properties, methods... Not much of highlight, it's nearly plain text.

**Comment by isagalaev** [comment]
It actually does look good to me, honestly. I understand it's subjective but that's how it is.
