### ISSUE TITLE
Failed to parse json error on linux (vagrant)

### ISSUE THREAD

**Issue by garypburton** [isagalaev/highlight.js#1148]
Hi there,

I am getting the following error when trying to npm install in vagrant (using Vagrant file setup from [here](http://fideloper.github.io/Vaprobash/index.html)).

```
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! file /vagrant/node_modules/.staging/highlight.js-6c74aa48/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected control character at 237:29
npm ERR!       "email": "me@stikhomir
npm ERR!                             ^
npm ERR! File: /vagrant/node_modules/.staging/highlight.js-6c74aa48/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```
It seems to vary what line in the package.json it fails at but it is always something in that file.

I don't if this is just related to vagrant as I can successfully npm install the same project on native OS X.

Any ideas?

Many thanks,

Gary

**Comment by isagalaev** [comment]
I'm not sure what causes it but I'm fairly sure it's not highlight.js itself for two reasons: we don't have the revision 6c74aa48 in our tree at all, and we don't have this contributor email in our package.json. May be some files from different packages get mangled along the way somehow?

**Comment by garypburton** [comment]
Hey thanks for getting back to me. That's weird maybe it is just something to do with vagrant folder synch. I had a look through the node_modules when it does work on OS X and in the package.json in the highlight.js folder there is this email in the contributors object:

```
{
      "email": "me@stikhomirov.com",
      "name": "Sergey Tikhomirov"
},
```
which is what the error above is complaining about. Although this doesn't appear in the package.json on your repo here... It looks like it is handlebars-helpers in my project (which is being used by grunt-assemble I think) that is requiring it at v7.4.

**Comment by isagalaev** [comment]
Our production package.json is generated from AUTHORS.en.txt, that's why you don't see any contributors in the one in the source. And the reason I didn't find that particular email in the current production package.json is that it was changed in b241a110.

But all that is beside the point anyway. The reason I think it's outside highlight.js is that the error points exactly after the `"me@stikhomir` which is arbitrarily in the middle of the email. I think something either gets cut off or mangled with other data coming from a different thread perhaps. But I'm afraid we can't help it from our side.
