### ISSUE TITLE
Wrong language detections in code blocks

### ISSUE THREAD

**Issue by obestwalter** [isagalaev/highlight.js#1149]
I have some wrong detections I would like to report here.

logging output like this is wrongly recognized as "stylus":

	root                53  main             : play_simple_game() ...
	mau_mau.subjects    28  invite           : invite [Player('Player 1', Hand([])), Player('Player 2', Hand([])), Player('Player 3', Hand([]))] to: Table(None, None)
	mau_mau.subjects    100 draw             : Player 1 <- Card('10', '♣')

shell examples with generic path placeholders are recognized as "regexp":

        $ cd </path/to/your/clone>
        $ mau-mau

See also here: http://oliver.bestwalter.de/mau-mau/guide/usage/ (generated with [MkDocs](http://www.mkdocs.org/) which is using highlight.js)

**Comment by isagalaev** [comment]
These mis-detections are due to inherent nature of heuristics, they can't be fixed. Highlight.js provides a means to explicitly disable highlighting on a block of code using a class name "nohighlight". An even better way to do it would be not marking it up as code in the first place and use `<pre><output>` combination instead of `<pre><code>`.
