### ISSUE TITLE
no `tools` directory

### ISSUE THREAD

**Issue by yibuyisheng** [isagalaev/highlight.js#1169]
There was no `tools` directory when I installed this library by `npm install highlight.js`, so I can not use the `tools/build` script to build for browsers.

**Comment by derhuerst** [comment]
The GitHub repo contains the `tools` dir. Also, check the [highlight.js website](https://highlightjs.org/download/).

**Comment by yibuyisheng** [comment]
@derhuerst Thanks for your answer.

I know what you mean. There are two workarounds:

* 1. `npm install isagalaev/highlight.js --save`, then I have a `tools` dir.
* 2. Download the [highlight.min.js](https://highlightjs.org/download/), and use the script tag to import it.

But my project is based on `npm modules`, so the two workarounds look really ugly.

I think the most perfect way is to publish the `highlight.pack.js` to `npm` too.

**Comment by derhuerst** [comment]
> I know what you mean. There are two workarounds:

> 1. `npm install isagalaev/highlight.js --save`, then I have a `tools` dir.
> 2. Download the highlight.min.js, and use the script tag to import it.

Or use a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and build the `highlight.js` on the fly.

> But my project is based on npm modules, so the two workarounds look really ugly.

I'd also like highlight.js to be many small modules, as that is the common practice in the npm eco system. See #1086.

> I think the most perfect way is to publish the highlight.pack.js to npm too.

I strongly disagree. There is a point in npm just serving the distribution files, as custom builds seems to get less common (because of small composable modules).

There's terabytes of traffic and hours or time being wasted because npm modules that have more files than necessay.

**Comment by isagalaev** [comment]
The purpose of highlight.js on npm is to be installed and used as a library, it's not a source code distribution. Source code is hosted on GitHub. We don't intend to support every imaginable way of getting either source or binary distribution from everywhere.
