### ISSUE TITLE
nesting pure begin modes

### ISSUE THREAD

**Issue by micimize** [isagalaev/highlight.js#1202]
I'm trying to add proper mode nesting to markdown, so that  nesting highlights works as expected (for example, \*\`emphasized code\`\* => *`emphasized code`*. What I'd really like to do is `returnBegin`, but I can't figure out how to prevent an infinite loop?

Here're some of the approaches I've tried, nesting the `contains` of `emphasis`, `code`, and `strong` accordingly:

| approach | `` {begin : '`.+?`'} `` |
| --- | :--- |
| input | ``*`code`* `` |
| desired output | *`code`* |
| failure output | *\`code\`*  |
| notes | nesting won't work because begin isn't searched | 

| approach | `` { begin: '`', end: `'` } `` |
| --- | :--- |
| input | `` `code ``   |
| desired output | \`code |
| failure output | `` `code ``  |
| notes | nesting kind of works, but we only want to format if the `end` is found |

| approach | `` { begin: '`(?=.+?`)' , end: '`'} ``      |
| --- | :--- |
| input | `` `code` ``  |
| desired output | `code` |
| failure output | \`code\`     |
| notes | on debugging it seems like only the lexeme `` "`code" `` is searched |

| approach | `` { begin: '`.+?`', returnBegin: true } `` |
| --- | :--- |
| input | `` `code` ``  |
| desired output | `code` |
| failure output | infinite loop |
| notes | how do you avoid an infinite loop here? |

**Comment by michaeljosephrosenthal** [comment]
@sourrust is there a way to prevent an infinite loop with both a pure `begin` mode and `returnBegin`?

**Comment by isagalaev** [comment]
To make the long story short, you can't parse nested things only using regular expressions, you need a stack for it. So the approach with trying to parse out the whole thing and then somehow rely on `returnBegin` wouldn't work anyway.

To do something like this you want to define a few modes that can happen inside each other, in this fashion:

```js
var INLINES = [];
var STRONG = {className: 'strong', begin: /\*\*/, end: /\*\*/, contains: INLINES};
var EMPHASIS = {className: 'emphasis', begin: /\*/, end: /\*/, contains: INLINES};
var CODE = {className: 'code', begin: /`/, end: /`/, contains: INLINES};
INLINES.push(STRONG);
INLINES.push(EMPHASIS);
INLINES.push(CODE);
```

As preventing infinite loops with `returnBegin`, you need to have something in the `contains` attribute of the mode to consume what was just returned. Otherwise, the very same mode would try to consume the returned part again, ad infinitum.

**Comment by micimize** [comment]
@isagalaev thanks for the in depth response. I haven't worked on the related project in a while, but that seems like sufficient info for when I go back to it. I guess I would want to have a different `INLINES` for each mode to prevent improper nesting of `STRONG` with `STRONG`
