### ISSUE TITLE
container styling: place the hljs class on the pre-tag instead?

### ISSUE THREAD

**Issue by episodeyang** [isagalaev/highlight.js#1224]
Currently Highlight js handles the `<pre><code>` tag by treating the `<code>` tag as the root container by default. 

As a result, this means that the `.hljs` class is assigned to the code tag instead of the pre tag.

Typically in a markdown renderer, the pre tag has padding because pre-formate blocks usually require so.

Because there is no way in CSS to remove the padding of the containing pre-tag, the `pre code` container have to share the css  padding with the other pre-formate blocks. 

Because `hljs` treats the inner code block as the root container, and apples the `.hljs` class to this node by default, there is a mismatch between the `background-color` of the pre-node and the code-node that is inside.

Also there is not the `pre` node padding plus the `code.hljs` node padding.

Would there be a  better way to handle this?

I have been using highlights for years, and this problem comes up quite frequently. I'm hoping that we can figure out a standard way so that people don't have to have the same CSS boiler plate everytime.

**Comment by episodeyang** [comment]
Hi, is there any update on this? If my comment is unclear I can future clarify.

**Comment by isagalaev** [comment]
Hi! Sorry, I'm lagging behind on answering bug mail.

There's a few ways to solve this, I think.

- First of all, you can certainly set 0 padding on `pre`. I'm not sure what do you mean by saying it can't be done in CSS.

- Alternatively, if you want all `pre` containers to have a certain padding and you don't want an extra padding added by `code` you can set it to 0 just as well: `.hljs {padding: 0}`.

- You could also initialize highlighting on `pre` nodes, instead of their `code` children. This will require some JavaScript to walk over all `pre`s, figure out if they contain `code` and then call `hljs.highlightBlock()` on parents.

**Comment by SH20RAJ** [comment]
Dev.to and GitHub usage pl Syntax Highlighter
 :- https://dev.to/sh20raj/devto-and-github-usage-pl-syntax-highlighter-3mo8
