### ISSUE TITLE
Inlining highlight.pack.js in script element fails due to "</script>"

### ISSUE THREAD

**Issue by fvsch** [isagalaev/highlight.js#1232]
Including the `highlight.pack.js` script as inline code, for instance:

```php
<script>
<?php echo file_get_contents(__DIR__ . '/highlight/highlight.pack.js'); ?>
</script>
```
leads to a HTML validity and parsing error, because the `highlight.pack.js` contains this string:

```js
"</script>"
```

which the browsers’ HTML(5) parsers interpret as closing the script element. (Theoretically, any `</` character sequence should close the element, but in practice browsers only close on `</script>`, and maybe this was specified in HTML5 as such, I’m not sure.)

One solution would be to escape as: `<\/script>`. This doesn’t change the JS string (once this code is parsed, the JS string is `"</script>"`).

**Comment by sourrust** [comment]
The change to the literal `</script>` happens during compression since it is [escaped in the source file][xml]. And looking into the compressor we use, the only option to escape `</script>` is in the [beautifier options][beauty]. So really, the only options you have are go uncompressed or not to inline the library.

[xml]: https://github.com/isagalaev/highlight.js/blob/master/src/languages/xml.js#L84
[beauty]: https://github.com/mishoo/UglifyJS2#beautifier-options

**Comment by fvsch** [comment]
For the record, if it helps anyone finding this issue: you can work around this issue on inclusion. For instance with PHP:

```php
<script>
<?php 
$source = file_get_contents(__DIR__ . '/highlight/highlight.pack.js');
echo str_replace('</script>', '<\\/script>', $source);
?>
</script>
```
