### ISSUE TITLE
Highlighting for YAML doesn't work with class="language-yaml"

### ISSUE THREAD

**Issue by markvincze** [isagalaev/highlight.js#1249]
I'm using highlight.js in a Ghost blog, which automatically generates the `language-` prefix in class names of `<code>` blocks. This works for certain languages with highlightjs, but for some reason it's not working with YAML.

I'm using the vs color theme.

Here is a jsbin showing the issue: https://jsbin.com/cedisabuke/edit?html,output

Is there a way to workaround this issue?

**Comment by sourrust** [comment]
https://jsbin.com/favoyijazi/edit?html,output

Please read the section about [CDNs in the README][cdns].

[cdns]: https://github.com/isagalaev/highlight.js#getting-the-library

**Comment by isagalaev** [comment]
To clarify more on detection. The first snippet uses "language-yaml", so highlight.js knows it is the language name and doesn't highlight the snippet because it doesn't have this language definition. The second snippet uses plain "yaml" and it would've been recognized as a language if highlight.js had it but in this case it sees it as a random class name, not a language, and tries auto detection which happens to be detected as "http".

**Comment by markvincze** [comment]
Ah, sorry, I missed that part of the docs.

This is great, thanks guys for the info!

**Comment by BenjaminHoegh** [comment]
I have the same issue just with every language, example: `language-html` dosn’t work but if i write `html` then it work
