### ISSUE TITLE
PHP HTML Mix View Not Working

### ISSUE THREAD

**Issue by JuanDiDiego** [isagalaev/highlight.js#1267]
Hello @isagalaev ,

I downloaded the latest version of highlight.js and I'm still having the issue that was talked about [on this ticket](https://github.com/isagalaev/highlight.js/issues/225).

I'm using PHP and HTML and when I preview the page the HTML doesn't show and it even looks like the HTML style gets applied.

**Code View:**
![screenshot from 2016-08-03 15-07-20](https://cloud.githubusercontent.com/assets/20046084/17437809/d753d93e-5aed-11e6-9c90-b84bc05c46cc.png)

**Browser View:**
Notice that the "p" tag does not show in the echo statement and the added space is due to the fact that the browser recognizes this as a paragraph.

![screenshot from 2016-08-03 15-06-45](https://cloud.githubusercontent.com/assets/20046084/17437812/de2f73bc-5aed-11e6-9b1f-117161480b52.png)

**Comment by isagalaev** [comment]
It doesn't look like having anything to do with the ticket you're referring to. `<p>` don't show up in the echo statement because in your source it's an actual HTML tag. If you want angle brackets to be displayed literally in HTML, you need to escape them with `&lt;` and `&gt;`. This doesn't even have anything to do with highlight.js, it's imply how HTML itself works.
