### ISSUE TITLE
Color scheme for atom one light not showing properly.

### ISSUE THREAD

**Issue by aryzing** [isagalaev/highlight.js#1295]
Highlighting html code with atom one light seems to not be working 100%.

For example, the first image is from the browser and the second is from the editor itself. Notice the difference in color of the attributes.

Browser:
![meta-browser](https://cloud.githubusercontent.com/assets/4924405/18323358/1dae75fc-74ec-11e6-95b3-045142d77eaa.png)

Atom:
![meta-atom](https://cloud.githubusercontent.com/assets/4924405/18323371/2a0e345e-74ec-11e6-820e-9dc33a1540b4.png)

I inspected the classes of the relevant spans, and found that they had been assigned `hljs-attr`. However, there is **no selector targeting** `hljs-attr` in the [CSS](https://github.com/isagalaev/highlight.js/blob/master/src/styles/atom-one-light.css). The CSS does have an `hljs-attribute` selector, but it does not set the color to the value we are interested in.

The color that should be applied is [this yellowish color](https://github.com/isagalaev/highlight.js/blob/master/src/styles/atom-one-light.css#L73).

**Comment by isagalaev** [comment]
On a general note, styles in highlight.js are not supposed to match exactly to other implementations of the theme. It isn't actually possible because of the differences in highlighting engines.

This particular change totally makes sense, though. We do have `.hljs-attr` specifically for this purpose. Could you make a simple pull request with this change for both variants of the Atom theme?

**Comment by aryzing** [comment]
Ok!

Yes, I'll submit a PR shortly
