### ISSUE TITLE
JS arrow functions and built-ins not getting picked up

### ISSUE THREAD

**Issue by aryzing** [isagalaev/highlight.js#1296]
JavaScript arrow functions and built-ins are not being picked up by hljs, so they appear as normal text (using atom one light)

Browser render and dom structure:
![js-dom](https://cloud.githubusercontent.com/assets/4924405/18324479/9a3d3b08-74f1-11e6-8eff-92fdebf696ed.png)

![js-hljs](https://cloud.githubusercontent.com/assets/4924405/18324442/5b6682d6-74f1-11e6-94fb-ffb954a2f414.png)

Atom:
![js-atom](https://cloud.githubusercontent.com/assets/4924405/18324444/5ef65584-74f1-11e6-8978-c31dbe045323.png)

Code text:
```js
// handle error
setTimeout(() => liveReload(last), 1000);
```

**Comment by isagalaev** [comment]
There's a couple different issues here:

- We can't afford having too many built-ins defined for common languages to keep the size of our default package down. In JavaScript we have core built-ins, but `setTimeout` is not one of them. (Technically, it's not even a built-in, it's a method on `window`.)

- We do recognize arrow functions since recently, but what we highlight is the list of parameters before `=>`. We don't highlight the arrow itself due to the general design choice in highlight.js to not highlight punctuation.

And just as a reminder, we don't have a goal to match other syntax highlighting engines. Highlight.js is less colorful than most, and it's a feature :-)

**Comment by aryzing** [comment]
I see. Thanks for clarifying :)
