### ISSUE TITLE
Replacing < > automatic with highlight.js 

### ISSUE THREAD

**Issue by wolfgang1983** [isagalaev/highlight.js#1333]
I would like to know if there is away when I have code in side my .code tag  if it can auto detect < > and replace them with html entities

```
<script type="text/javascript">
$('#preview-question').on('click', function (e) {
    var editor = $('#question').val(); 
    $('.preview').html(editor); 
    $('.preview pre').each(function(i, block) {
        hljs.highlightBlock(block);
        $('.preview pre').wrapInner('<div class="code"></div>');
    });
});
</script>
```

**Comment by logicplace** [comment]
It can only be done before the browser interprets the file as HTML. That is, it can only be done in an HTML preprocessor. Since you're grabbing the content from the editor, you can do this yourself before $('.preview').html(editor); but highlightjs can't do it for you. http://stackoverflow.com/a/5499821

**Comment by isagalaev** [comment]
Yes, this is it. Thanks @logicplace!
