### ISSUE TITLE
JavaScript single-line comments interpreted as regex

### ISSUE THREAD

**Issue by jlmakes** [isagalaev/highlight.js#1534]
I am using `highlight.js` `v9.11.0`.

It seems certain word combinations cause the double slash of single-line comments to be interpreted as an empty regex, and then highlighting the comment body as strings and keywords.

![screen shot 2017-05-28 at 8 25 27 pm](https://cloud.githubusercontent.com/assets/2044842/26531186/2677702c-43e4-11e7-8976-292c747cb601.jpg)

![screen shot 2017-05-28 at 8 27 32 pm](https://cloud.githubusercontent.com/assets/2044842/26531190/2e0b9c1e-43e4-11e7-88ef-17a855781484.jpg)

A simple workaround I've found is to use `/* ... */` multiline comment syntax, but what’s strange, is that by simply removing _one_ of the "keywords" the comment displays correctly:

![screen shot 2017-05-28 at 8 25 57 pm](https://cloud.githubusercontent.com/assets/2044842/26531198/665ef12e-43e4-11e7-8fe1-543a8b541996.jpg)

![screen shot 2017-05-28 at 8 26 34 pm](https://cloud.githubusercontent.com/assets/2044842/26531199/694f1c10-43e4-11e7-9c10-9c8393e322ea.jpg)

![screen shot 2017-05-28 at 8 26 50 pm](https://cloud.githubusercontent.com/assets/2044842/26531200/6b9fd4be-43e4-11e7-9645-8f03ea9aeb4a.jpg)

What is even **more strange**, is that on a different page of mine with a virtually identical comment... I don't have this same issue! (Even the syntax highlighting is slightly different!)

![screen shot 2017-05-28 at 8 40 12 pm](https://cloud.githubusercontent.com/assets/2044842/26531262/e3c7aea2-43e5-11e7-9f87-d1b190cad6a4.jpg)

Please let me know what more information I can provide that may help anyone willing to help me troubleshoot this. Thank you!

**Comment by isagalaev** [comment]
All of these are due to failing language detection heuristics, and on small examples like these it's basically unsolvable, unfortunately.  (The last example is triggered into the correct detection by the string `'100%'` which does have a relevance weight, while numbers don't. Tuning it is a tricky business!)

One straightforward way to fix this is to specify the language explicitly which is done in highlight.js with `class="language-js"` on the `<code>` element (which is how HTML 5 recommends it). The `data-language` on `<pre>` does nothing for highlight.js so we just do auto detection.

**Comment by jlmakes** [comment]
I really appreciate the prompt reply @isagalaev 

I tried adding the class name as you described, but I didn't observe any difference:

![screen shot 2017-05-28 at 10 05 06 pm](https://cloud.githubusercontent.com/assets/2044842/26531825/19721efa-43f2-11e7-945a-2e6dab30223a.jpg)

For what it’s worth, I don’t mind using the `/* ... */` syntax... but if there is a way I can be explicitly declaring JavaScript, that does sound like a good idea. For reasons I don’t recall, I was under the impression that the `data-lang` attribute was doing just that.

**Comment by isagalaev** [comment]
Hm… I can't seem to reproduce the bug. Have a look: https://jsfiddle.net/yxcpLwt9/
Removing `class="language-js"` (and refreshing the result with the Run button in the top left corner) does indeed produce a broken highlighting due to misdetection, but `language-js` fixed it.

One thing I can think of is that may be your bundle of highlight.js doesn't have JavaScript in it? Try looking in the console at what `hljs.getLanguage('javascript')` returns. It should be a language object.

**Comment by jlmakes** [comment]
I think I‘ve found the problem.

I’m using `gulp-highlight` as a wrapper for highlight.js in my build process, and after inspecting the source, I see that it only uses the `hljs.highlightAuto()` method. I believe that explains why I can't explicitly set the language.

Thanks for your help @isagalaev.

**Comment by isagalaev** [comment]
Ah, that explains it… You can always call the highlighting function manually, it's just a one-liner:

```js
Array.prototype.forEach.call(document.querySelectorAll('pre code'), hljs.highlightBlock);
```

**Comment by jlmakes** [comment]
Just a quick follow up to say thanks!

I was able to review the highlight.js source, and refactor `gulp-highlight` to support language class detection. I’ve submitted a PR, so hopefully this can be fixed for future developers. In the mean time, my local environment is the 💣

**Comment by isagalaev** [comment]
Glad to hear it! :-)
