### ISSUE TITLE
Language mode file pattern

### ISSUE THREAD

**Issue by tenbits** [isagalaev/highlight.js#663]
Hi Devs, you may want to close this issue, as it is actually not the problem at all and I used not to share such things via gh-issues, but this one has surprised me a little: _All files in `languages/*` are not valid javascript_ :hushed:. I know, there is a build tool for this, but it would be definitely better to have `hljs.registerLanguage()` with inside the each language mode. The benefits were:
- **Standalone**: each mode would be a real standalone unit: include, reload etc.
- **Core only**: I would prefer the modular architecture: single highlightjs core (perhaps with some basics) and then consumer decides what modes to `require`, `include`,`define`.  But all-in-one package is also nice to have.
- **Simple build**: The build tool would be much simpler: less code generation, without interpolations - just concat the mods.

Hope my feedback was helpful, but anyway thanks for your work: very nice and clean library.
Cheers, Alex

**Comment by isagalaev** [comment]
Getting back to this one… I've read the proposal again and it seems that the benefits aren't clear at all:

- Having standalone modules hosted on GitHub is something that I resist very much because it means people will start using master in production code and we'll be under more pressure to not break compatibility even by transitive commits.

- Wrapping language functions is a very small part of the build tool functionality so getting rid of that won't really change things: the build tool will still have to resolve and order dependencies, generate the demo app, etc.

Closing this issue for now, though I want to make it clear that I'm not against simplification of our module structure. I just don't see the solution yet.
