### ISSUE TITLE
Add "deselect all / select all" buttons, to Download >> Custom Package

### ISSUE THREAD

**Issue by eksperimental** [isagalaev/highlight.js#687]
It will be really helpful to have a button to select all or none, in https://highlightjs.org/download/
as if i only one i need to untick the checkboxes one by one.

**Comment by isagalaev** [comment]
The "Select All" button is absent for a reason, I'd like to specifically discourage the idea of downloading the entire language archive for using in a browser. The resulting file is huge (300K as of now and is only going to grow more) and having those on the Web will create the impression that highlight.js is slow and buggy due to mis-detection errors with little used languages. If one really wants to have a package with MEL, G-Code, Stata and Smali and what-not, then I could recommend simply building one manually.

@Sannis  as for opening the sites code, there's little value in that because I will still be the bottleneck since I have to review code, manually apply those updates and maintain the dependencies, etc. Also, I will have to give up the luxury of keeping the code in bzr and switch to this git thing that I never liked :-)
