### ISSUE TITLE
Issue with Elixir highlighting

### ISSUE THREAD

**Issue by whatyouhide** [isagalaev/highlight.js#707]
This HTML snippet:

```html
<html>
  <head>
    <link rel="stylesheet" href="highlight/styles/default.css">
    <script src="highlight/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>

  <body>
      <pre><code class="elixir">defmodule Foo do
  def foo, do: :foo
  def bar, do: :bar
end</code></pre>
  </body>
</html>
```

produces this buggy result:

![screen shot 2015-01-11 at 22 23 25](https://cloud.githubusercontent.com/assets/3890250/5696886/7cbd87f6-99e0-11e4-9ca0-32396c0f7c33.png)

because of the `def f, do: # code` syntax (as an alternative to the usual `do`/`end` block, which works just fine). I think @knewter took care of the Elixir highlighting, so if he has a quick fix that would be great! Otherwise, I'll try to start working on it as soon as I can. I never contributed to highlight.js though, so it could take me a while to get familiar with it :disappointed:.

**Comment by Sannis** [comment]
Am I right that with this syntax funcation body ends with new line? (`\n`)?

**Comment by whatyouhide** [comment]
@Sannis I don't think so. The `do:` is followed by an *expression*. Some examples of valid Elixir code:

```elixir
def foo, do:
  3 + 5
```

or

```elixir
def foo, do: 3 +
             4 +
             5
```

The first of the above examples is highlighted **incorrectly**, while the second one is highlighted without any errors.

**Comment by tonini** [comment]
@Sannis @whatyouhide The issue is that the elixir highlightjs extension treat `do:` as `symbol` instead a `keyword`.

@Sannis I have not really looked into the good of highlightjs and the elixir extension, but shouldn't that more or less easy to fix?

Thanks

Samuel

**Comment by tonini** [comment]
@Sannis @whatyouhide What is the status about that? we really would like to fix this because we love to use it in `ex_doc` :-)

Before I'm starting looking into it by myself, maybe you guys can have a quick look before me. :)

@knewter I know you have a lot to do, but if you got a few minutes, please have look. :heart: :-)

**Comment by whatyouhide** [comment]
Any news on this? As @tonini said, we would really really love to fix this since it's screwing up *a lot* of examples in Elixir's documentation (as well as in the documentation of every library using `ex_doc`, i.e., every library :smile:).

**Comment by knewter** [comment]
Urk, what's the situation with the tests these days?  `src/test.html` isn't
a thing anymore, and `test/index.html` doesn't really trigger anything
(don't know that it should).  Is there documentation on how to add new
language support re: testing/verifying?  Because I was going to fix this
today and realize it's changed too much for me to get it done in 15 minutes
or so :(

On Fri, Jan 30, 2015 at 9:06 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Any news on this? As @tonini <https://github.com/tonini> said, we would
> really really love to fix this since it's screwing up *a lot* of examples
> in Elixir's documentation (as well as in the documentation of every library
> using ex_doc, i.e., every library [image: :smile:]).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/707#issuecomment-72214373>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

**Comment by isagalaev** [comment]
@knewter the docs on testing are here: http://highlightjs.readthedocs.org/en/latest/building-testing.html (in short, we now have tools/developer.html to play with markup).

I'm not sure when any one of us will be able to look into it (for me it's probably next Tuesday), so feel free to pick it up.

**Comment by knewter** [comment]
I'm looking at it now, we'll see if anything comes of it /cc @tonini @whatyouhide

**Comment by knewter** [comment]
so @tonini @whatyouhide @josevalim I have a few questions about this one.  In this case, *isn't* do an atom in an optionlist?  That's the core problem here - it's matching "thing: other" such that thing is an atom in the list.  That's matching do.  I can change the regex such that do isn't matched, in which case it would become a keyword...but then you would always get that behaviour if you used do: in an optionlist as well, which is wrong (but better?)  Basically, I need to do this work when @josevalim or someone is around to help explain to me my misunderstandings like this in the parser.  Sadly the highlight.js syntax checking is in no way presently easy to 'port' from the actual tokenizer in elixir, primarily due to my lack of experience here (only parsers I've really written that were complicated were PEGs)

**Comment by whatyouhide** [comment]
@knewter I think the problem is not that `do:` isn't highlighted as a keyword (it's not, it's just an atom and that's fine). The problem is that all newlines after a `do:` get messed up.

Note that this is valid Elixir syntax:

```elixir
%{a:
  3}
```

or

```elixir
[do:
  something]
```

**Comment by knewter** [comment]
Aha I missed the point entirely :)

**Comment by isagalaev** [comment]
Am I getting this right that in the case of

    def foo, do: :foo

The comma `,` actually signals the end of the function header and that `do:` is something else entirely than in the case of

    def foo do
      # ...
    end

?

**Comment by eksperimental** [comment]
@isagalaev what comes after `, do:`  should be treated the same way as what's in between `do` and `end`, with the exception that that `, do:` cannot accept new lines, and `;` and `( )` are used instead.
I don't know if that answer your question.

```elixir
def foo, do: (IO.puts "hello"; IO.puts " world")
```

produces internally the exact same code as:
```elixir
def foo do
  IO.puts "hello"
  IO.puts " world"
end
```

**Comment by isagalaev** [comment]
Ooookay, I think I've fixed it, finally:

![elixir-functions](https://cloud.githubusercontent.com/assets/99931/6717150/c5c6b84a-cd67-11e4-808f-3a9da2c8c35f.png)

I even had to introduce a new functionality in the core for that :-) Which I hope is going to be needed for another bug elsewhere.

**Comment by josevalim** [comment]
Awesome, thank you!

**Comment by eksperimental** [comment]
much appreciated @isagalaev !

**Comment by whatyouhide** [comment]
Awesome @isagalaev, thanks so much! :heart:

**Comment by knewter** [comment]
This is great. I can stop feeling terrible now! :heart:
