### ISSUE TITLE
highlight.js removes mouseover event listener from child anchor w/ tooltip

### ISSUE THREAD

**Issue by imjoeybrennan** [isagalaev/highlight.js#728]
So I'm trying to put a bootstrap tooltip on an anchor I put inside the code block that I put highlight.js on but I can see highlight.js is removing the mouseover event listener on the anchor. How can I either add this back or refrain this from happening to that anchor specifically?

**Comment by isagalaev** [comment]
This happens because we generate new HTML markup to replace the existing one and we keep all the old tags and attributes but not the dynamically assigned event listeners ([source][]). I don't know if those are discoverable through DOM so we could retain those too.

One thing you could do is to run the Bootstrap init code after the highlighting. Will that work for you?

[source]: https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L123

**Comment by Sannis** [comment]
@imjoeybrennan, can you please post some example of code you are using and Bootstrap version?

It looks like you should use "live" events for tooltip handling and there was some stories how to do that: http://stackoverflow.com/questions/9958825/how-do-i-bind-twitter-bootstrap-tooltips-to-dynamically-created-elements

**Comment by Sannis** [comment]
Closing this as outdated issue without activity.

**Comment by rmannibucau** [comment]
Hi, same there, my workaround is to 1. run highlightjs, 2. use jqeury.hover (but same with plain js/html coding behaves the same). Would be great for highlightjs to keep existing callbacks on dom elements (or propagate them on replaced ones).

**Comment by joshgoebel** [comment]
> Would be great for highlightjs to keep existing callbacks on dom elements

How would this even be possible if we entirely replace the HTML?

> or propagate them on replaced ones

Not sure what you mean, do you have an example?

---

If this is possible someone would be welcome to write a plugin that does this!  We have before and after callbacks...

**Comment by joshgoebel** [comment]
> You wrap the nested element in a span or equivalent and attach to it the original listeners. 

Example code?  I wasn't aware you could query an element and get it's existing listeners.

> Technically highlight.js is about formatting a text

True.

>  but not destroying the contained actual dom

Actually, our current POV and policy is that code/text [to highlight] should NOT contain DOM at all. We feel 95% of the time it's an accident that often leads to security issues, code injection attacks, etc.  The other 5% is better served by someone willing to upkeep and maintain a plugin for these cases - we have the plug-in APIs - yet no one has volunteered to step up.

>  there is no real strong reaons.

I've written enough on this topic but there are definitely strong reasons, and a lot of them involve defaults and security.

> Side note: it is even more important when used as highlighter with a 3rd party like asciidoctor where the plugins are way harder to inject and the issue to understand for most users IMHO.

3rd party tools should expose our easy API endpoints, if they do not I'd file an issue against those tools.

**Comment by rmannibucau** [comment]
> Example code? I wasn't aware you could query an element and get it's existing listeners.

Requires some "verbosity" on listing the callbacks but `if (element.onmouseover) propagate(element, target, "onmouseover")` kind of code should work, just needs to list supported callbacks in an array or alike somewhere and loop over it IMHO.

> Actually, our current POV and policy is that code/text [to highlight] should NOT contain DOM at all.

Well, there are still very common and expected/very valid use cases like links and tooltips (ie all use cases which are not about formatting/structuring but rather interacting). This is also the use cases where the callbacks are the most important sadly.

> 3rd party tools should expose our easy API endpoints, if they do not I'd file an issue against those tools.

Well, consumer eat a highlighter which is supposed working and here the bug is clearly in the highlight.js destruction of the dom, not in any other 3rd party so I don't think it is sane to move the workaround in all consumers ;).

What about a compromise like a highlight.js data attribute to enable the propagation of listeners: `<code class="language-xml hljs" data-highglighjs-keepNestedCallbacks="onmouseover,click">...</code>`.

**Comment by joshgoebel** [comment]
> if (element.onmouseover) propagate(element, target, "onmouseover")

That's very old school API.  Does the browser map `addEventListener` events into those old attributes?  If not, that's not very useful for many cases.  Plus you can have multiple event listeners attached to an element, not just one... just highlighting the code while leaving existing DOM in place is not a trivial problem to solve AFAIK.

> What about a compromise

Write a plugin that makes it happen and add it to the wiki. :-)  I doubt it's as simple as you think though (for _general_/wide use cases).

> there are still very common and expected/very valid use cases 

We'll disagree on "very common"... or you'd think we could find someone willing to step up and write/maintain a plugin (esp. if it was easy to do so).   

>  bug is clearly in the highlight.js destruction of the dom

If there is a bug here, it's that we "destroy" the DOM without documenting it clearly.  _So we plan to fix this in version 12._  I'd fix it right away but it's a breaking change.  In version 12 we will simply error, period, leaving the DOM intact and explain we simply do not support this (with a link to why).  That fixes the bug - then it's merely a "lack of feature", which again anyone is free to fill with a plugin.

**Comment by rmannibucau** [comment]
Yep, `addEventListener` requires more careness - typically overriding the default one (+ remove flavor) to be able to query the additions/removals but still something fairly doable even if it would require to bind highlightjs before.

Do you mean you plan to not support highlighting any code with any dom tag in v12? Sounds like killing the project.

About the plugin option, I'd really like to avoid it since, from my experience, plugins tends to be poorly maintained if not in the core project - which creates a lot of mess after very few time and upstream releases.

But I'd like to come back on the "is it common or not" point: do you mean you don't want highglight.js to handle interactive code snippet at all? Cause it is exactly what we are talking about. It does not sound crazy to me in 202x to be able to have a link/anchor and tooltip in a code snippet, do you think it is?

**Comment by joshgoebel** [comment]
> Do you mean you plan to not support highlighting any code with any dom tag in v12?

**We already don't.**  We strip them completely and have since version 11.  The project lives on.  Your use case is not the 99% of use cases.   95% of code blocks are pure text. Perhaps 4% are text + HTML that's been inadvertently injected (a security issue waiting to happen).  The other 1% is your use case, and one that - given its complexity and security considerations simply doesn't make sense for us to deal with.

>  do you mean you don't want highglight.js to handle interactive code snippet at all?

Not at all, as I've said this is exactly why we have an plugin API - to support the 1% use cases.  I think it's an edge case and that the large majority of our users are better served by us closing the door on HTML injection attacks completely.  The more advanced users can figure out how to do this on their own (via plugin, etc) - or find alternatives.

**Comment by rmannibucau** [comment]
Ok got it, i'm a bit disappointed as you can guess cause I really like highlightjs since years and really hoped it could support dynamic callouts without any hack but well, hacks are working for now so could be worse, just hoping it does not break too much with future versions.

Anyway, thanks for the fast feedback!

**Comment by joshgoebel** [comment]
Out of curiosity, what is your "hack"?

**Comment by rmannibucau** [comment]
1. disable default highlightAll() (auto by default in the CMS i'm using)
2. force an eager highlightAll()
3. find anchor links from the source code (guess this one can break in the future) and enable the tooltips - i'm using bootstrap flavor. Doing it after 2 makes highlightjs not going back over the dom so I can inject the listeners/modify it as needed since it will not be destroyed

Not mal hack flow would be to bind the tooltip on the link and let highlighjs run after.

**Comment by joshgoebel** [comment]
> find anchor links from the source code 

How would you do that?

**Comment by rmannibucau** [comment]
@joshgoebel for now I use something like https://gist.github.com/rmannibucau/2d5c4635d313ecf45a2911d5c97a392d
