### ISSUE TITLE
ClojureScript packaging

### ISSUE THREAD

**Issue by shaunlebron** [isagalaev/highlight.js#761]
This project's build script packages a minimized core js + desired languages into a single file.  Would you consider an option to output these as separate files? (i.e. core file, lang1 file, lang2 file).

Having the separate pieces of the library as separate files allows us to defer the inclusion decisions to other build systems.  The recent standardization of how ClojureScript imports JS libs would benefit from this.

```clojure
(ns example
  (:require
    highlight
    highlight.html
    highlight.javascript))
```

**Comment by Sannis** [comment]
Why you cannot use npm build for that?

**Comment by isagalaev** [comment]
In fact, you have two different options:

- Use the raw source to build whatever you need. We specifically keep it free from any packaging convention to allow for any build target. So the core and every language are just JavaScript functions in separate files that can be wrapped in something.
- As @Sannis said, use the NPM build which keeps all the languages and the core separate but wraps them into the CommonJS interface with `module.exports`.

**Comment by shaunlebron** [comment]
I mean, if I was doing this outside the build script, I would definitely write my own thing to split the browser target __highlight.pack.js__ into separate files so that we benefit from the minification steps and we wouldn't have to make assumptions on what to wrap the language files with (i.e. `hljs.registerLanguage`).

So I thought this could be inserted as an option to the build script to get the intermediate output that already exists before concatenation.  Would you accept a patch for this?

(npm build is specific to commonJS and non-minified)

**Comment by isagalaev** [comment]
Let me lay out my thoughts one by one, as I seem to have trouble to make a coherent point today, sorry :-)

- Actually, the browser build is compressed *after* it's concatenated, so you can't just have separate compressed files for free. And I'd be against reordering that because it would make the build way slower (we tried).

- The separate compressed language files are useless as-is, they have to be wrapped in some code registering them with the library. If ClojureScript has its own module convention then the best way is probably make a separate build target, not an option for the browser build (but see the next point).

- There's another build type — "cdn" — that may be closer to what you need. It creates separate minified language files in the form `hljs.registerLanguage('<language name>', '<file contents>');`. The core library is usually bundled with some common languages but it can be avoided with `node -t cdn :none` to get the pure library core.

What do you think?

**Comment by shaunlebron** [comment]
The "cdn" build is perfect!  Thanks for clearing up the options @isagalaev

**Comment by isagalaev** [comment]
OK, glad it worked for you. We probably have to document it better.

**Comment by shaunlebron** [comment]
@isagalaev we found cdn build hosted [here](https://github.com/highlightjs/cdn-release/tree/master/build).  Could I submit a PR there to add a `highlight.core.min.js`?  (for no integrated languages)

**Comment by isagalaev** [comment]
@shaunlebron that repo is a verbatim source for our CDN hostings and it is updated by a script, so adding manually a file there will be obsolete as soon as a new version is released.
