### ISSUE TITLE
OCaml polymorphic variants are broken

### ISSUE THREAD

**Issue by SGrondin** [isagalaev/highlight.js#779]
The backtick character in OCaml signifies a polymorphic variant, it is not a comment.

See http://i.imgur.com/goeH2uu.png

Thank you

**Comment by ahmadnassri** [comment]
a little more context, we're using `<code class="ml"></code>` but it seems to overwrite as "coffeescript"

![image](https://cloud.githubusercontent.com/assets/183195/6628767/9530d86a-c8de-11e4-8dc0-2c7ef1f8c578.png)

**Comment by isagalaev** [comment]
If highlight.js doesn't recognize "ml" in the class attribute it is most certainly because the build you're using doesn't have OCaml definition in it. For example, if you're using the CDN hosted build then this is the case.

**Comment by isagalaev** [comment]
Another reason is you may use an older version that didn't yet know OCaml by the "ml" alias.

**Comment by ahmadnassri** [comment]
@isagalaev using what seems to be the latest from cdnJS: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js

**Comment by isagalaev** [comment]
@ahmadnassri yes, the cdnjs build simply doesn't contain OCaml. You'll need to get a custom build from https://highlightjs.org/download/ with the language *or* if you only need OCaml, you can link it from cdnjs individually:

```html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/languages/ocaml.min.js"></script>
```

**Comment by ahmadnassri** [comment]
ah, I ss what you mean now... I originally thought you meant the cdn version was behind a version ...

**Comment by ahmadnassri** [comment]
@isagalaev is there a way to dynamically load languages, or even a list of what's available by default?

**Comment by isagalaev** [comment]
The way to dynamically add languages is what I've shown before: a `<script>` tag referring to an individual language. The list of languages that are pre-packaged with the core is available on https://highlightjs.org/download/ under "Custom" title. The list of all language files is best seen here in the source: https://github.com/isagalaev/highlight.js/tree/master/src/languages.

I wouldn't recommend to add a lot of languages as separate scripts because that would be slow. Instead you can download a single custom package with all the languages you need.

**Comment by SGrondin** [comment]
Thank you
