### ISSUE TITLE
C++ WinApi keywords not supported?

### ISSUE THREAD

**Issue by PELock** [isagalaev/highlight.js#782]
Standard WinApi keywords like "NULL", "BOOL" aren't highlighted in "cpp" mode.

**Comment by isagalaev** [comment]
Well, they aren't really part of the language but rather a library `#define`s (if I remember correctly). We could add such words in some cases but cpp.js is already big enough and I don't want to go on the slippery slope of adding more stuff that someone else would consider standard or widespread.

So in other words, this is by design :-)

**Comment by PELock** [comment]
Maybe they are not the part of the language but they are a BIG part of the C++ world.

It's just poor highlighting. SyntaxHighlighter with C++ parser from 2006 can highlight more things than highlight.js in 2014 :+1: 

http://alexgorbatchev.com/SyntaxHighlighter/

And yes, I would have to switch back to it, who needs a syntax highlighter if it doesn't highlight anything? :-1:

**Comment by isagalaev** [comment]
Highlighting as many things as possible was never a goal for highlight.js. So please choose whichever highlighter works best for you!

P.S. It's 2015 already :-)

**Comment by PELock** [comment]
So you've wasted a whole year and still you're too lazy to add some popular keywords to your highlighter ;), you're one stubborn person :)
