### ISSUE TITLE
MATLAB syntax highlighting does not work properly

### ISSUE THREAD

**Issue by AkshatM** [isagalaev/highlight.js#819]
highlight.js is currently being used by [GitLab](https://about.gitlab.com) for syntax highlighting purposes. My team is running into issues with syntax highlighting in MATLAB files. Could this possibly be fixed? 

Here's an example:

![gitlabfile](https://cloud.githubusercontent.com/assets/6730980/7057589/0bd132b6-de0c-11e4-8414-8a0e2e1d2f6b.png)

In particular, comments in MATLAB (indicated by a % sign) appear to be ignored, and it's currently failing to detect the end of a string, leading to it highlighting all the following lines as well. 

This is not a GitLab issue [according to the community](https://gitlab.com/gitlab-org/gitlab-ce/issues/777).

**Comment by isagalaev** [comment]
It is not a bug in Matlab highlighting, but rather a mis-detected language. As noted in the downstream issue you referenced, GitLab currently uses file extensions to determine language for highlighting, and the extension ".m" is currently mapped to Objective C in highlight.js. Switching to auto detection in GitLab should fix this particular case. However auto detection is just another kind of heuristics, and it won't always work correctly either. Still, it's better than trying to highlight Matlab files as Objective C indefinitely.

What we could do, though, is to remove "m" as an alias for Objective C, because it appears to be a [pretty widely used extension][1].

[1]: http://fileinfo.com/extension/m
