### ISSUE TITLE
Feature request: regex for keywords

### ISSUE THREAD

**Issue by WolfgangKluge** [isagalaev/highlight.js#827]
I (try to) create a regex mode and there are some language constructs that I want to highlight, but I cannot - at least not the way I want to ;)
For example, I want to highlight `test` in
```
(?<test>subexpression)
```
Since `test` is a variable name, I cannot highlight it with `keywords`. But I also cannot match it with `contains` since `<test>` is a valid `subexpression` (where the word "test" is no longer any special), too.

My proposal is to extend `lexemes` It could be something like
```javascript
{
  lexemes: { 
    keywords: '\\b\\w+\\b', // search for keyword to match
    variable: 'regex for parts of the text that are always highlighted'
  },
  keywords: {
    keyword: '..'
  }
}
```
where `lexemes.keywords` maintain downward compatibility while the text matched by the regular expression `lexemes.variable` is always wrapped into `<span>`s in the generated markup.
`lexemes.keywords` should have a lower priority than every other `lexemes.*` regular expressions.

As a bonus, with this change you are able to higlight parts with whitespace in it (e.g underlined)...

**Comment by Sannis** [comment]
@isagalaev, what are you think about this?

**Comment by isagalaev** [comment]
Sorry for letting it hang, but I only now seem to finally get the problem.

    (?<test>subexpression)

To highlight the `<test>` following the first question mark and not any further you could define it like this:

```js
{
  contains: [
    {
      className: 'variable',
      begin: /\?</, end: />/,
      excludeBegin: true, excludeEnd: true
    },
    {
      endsWithParent: true,
      contains: COMMON_REGEX_STUFF
    }
  ]
}
```

The way it works is the first mode will match at the beginning and will highlight anything between `<..>` as you'd expect. The second mode will match anything at all and will end only when the parent mode ends. It is important to define 'variable' before the eat-everything mode to give it a chance to match first.

**Comment by WolfgangKluge** [comment]
Thanks for answering..

Every time I try to deal with `exclude*` I get into an endless loop (or it won't work either)... Nevertheless, I don't think this would work as I want.

Here is an extended, but still perfectly valid example: `(?<a>x?<b>(?<c>))`
What I want to achieve:
- `(?<`, the first `>` and the last `)` should all be colored the same (group)
- `a` should be marked special (variable)
- the second `(?<` and subsequent `>` and `)` around `c` should be marked as group, too. Maybe (but not necessarily) with a different className based on the group level
- `c` should be marked as variable, too
- the remaining parts are `x` (literal), `?` (quantifier), and `<b>` (literal!)

At the end it should look something like this:
![regex](https://cloud.githubusercontent.com/assets/639482/7965759/dd87fd1e-0a1f-11e5-9a18-b366155dd64c.png)

If possible, I would try to give the different variable names different classNames (so `a` and `c` have different colors, but every occurence of them is equally colored)... But that's something for later ;)

As I understand it, there are two problems left:
- ensure, `?<b>` is not matched by the first mode.
- highlight `?<` and `>` (although these parts are excluded)

I don't think that's possible this way - or I just don't get it ;)

**Comment by isagalaev** [comment]
Sorry for being a bottleneck in the conversation, I can only spend one day a week on highlight.js these days :-)

This is what I came up with:

```js
function(hljs) {
  var COMMON_STUFF = []; // populated later
  var GROUP = {
    className: 'group',
    begin: /\(\?</, end: /\)/,
    contains: [
      {
        className: 'name',
        begin: /\w+/, end: /\>/, excludeEnd: true,
        starts: { // everything else within a group
          endsWithParent: true,
          contains: COMMON_STUFF
        }
      }
    ]
  };

  COMMON_STUFF.splice(0, 0,
    GROUP,
    {className: 'quantifier', begin: /\?/}
  );

  return {
    contains: COMMON_STUFF
  }
}
```

Here's how it works:

- A `GROUP` is defined as starting with `(?<` and ending with `)` — pretty straightforward so far.
- The first thing it contains is `\w+` for 'name' and it matches immediately after the beginning of a group.
- The name then uses `starts` — a mode that forcibly start after this one is closed, hence it doesn't need a `begin`. And instead of an explicit `end` it uses `endsWithParent` (i.e. the group).
- This nameless all-the-rest mode contains everything that a regex can contain using a pre-declared array `COMMON_STUFF`. We can't simply refer to `GROUP` from inside of its own definition and anyway it should contain everything else too.

These are the two common patterns used in highlight.js:

- a mode starting with a predictably defined title portion that then starts all-the-rest portion
- allowing for nesting by first defining a container and populating it later

P.S. I'm pretty sure that your endless loops were coming from `returnEnd` and `returnBegin`, not `exclude*`: the latter simply controls where the output markup goes while the former actually rewind parser state and require extra care.

**Comment by WolfgangKluge** [comment]
Thanks again!
I still think it's way too complex to get some things done, but you put me back on the right track again..

**Comment by isagalaev** [comment]
@WolfgangKluge are you still on it? Just checking :-)

**Comment by WolfgangKluge** [comment]
Not with full effort.. I've a version that works me..

**Comment by isagalaev** [comment]
Ok, I'm going to close the ticket then. I agree that our current toolset is not adequate and has to be hacked around at times. I have a plan to rework it, however, into a more traditional parser approach.
