### ISSUE TITLE
C++: incorrect highlighting of identifiers that contain _t

### ISSUE THREAD

**Issue by jcmoyer** [isagalaev/highlight.js#875]
It seems [`CPP_PRIMATIVE_TYPES`](https://github.com/isagalaev/highlight.js/blob/master/src/languages/cpp.js#L9-L12) is a bit overzealous:

![Imgur](http://i.imgur.com/WE2m1TQ.png)

If it's OK to revert the commits (aa342e01...badb33fb) this was introduced in I can submit a PR.

**Comment by sourrust** [comment]
Thanks for pointing out this issue. I fixed it without having to revert the commits.

**Comment by jcmoyer** [comment]
It doesn't seem desirable to have user-defined types ending in _t to be highlighted like keywords.

**Comment by sourrust** [comment]
Since this is a common language it is included in the CDN release and saving space is something that is desirable. We did something similar in [objective-c][1] as well but it is more restrictive compared to this one. Plus the convention for the standard library in C and C++ is that names ending in `_t` are type so I figured, rather that have every type included in the standard library, just have something like this.

[1]: https://github.com/isagalaev/highlight.js/blob/master/src/languages/objectivec.js#L9

**Comment by isagalaev** [comment]
Another way of defining those would be longer regex like `(w|u)?(char|int|intmax)(8|16|32|64)?`. It's incredibly boring to compile though so frankly I gave up :-). I can live with the current overly general `[a-z\d_]+` but if someone is courageous enough to take on a stricter set — you're welcome!
