### ISSUE TITLE
TypeScript highlighting chokes on some casts

### ISSUE THREAD

**Issue by danquirk** [isagalaev/highlight.js#878]
Reviewable.io uses highlight.js and I tried to create a code review using it here https://reviewable.io/reviews/Microsoft/TypeScript/3642 and as you can see my code is essentially not highlighted at all. 

@pkaminski thinks the cause is a cast like:
```ts
return getModuleInstanceState((<ModuleDeclaration>node).body);
```
causing the highlighter to go into an XML mode and then never get back to TypeScript syntax.

TypeScript will be supporting JSX in the near future so the syntax coloring around <> will get even more complicated.

**Comment by pkaminski** [comment]
Yeah, I'm pretty sure [this production](https://github.com/isagalaev/highlight.js/blob/master/src/languages/typescript.js#L56) triggers XML mode when it sees the cast, but it's not clear to me how to distinguish between a cast and a JSX fragment.  @danquirk, do you know how the TypeScript parser deals with this ambiguity?

**Comment by danquirk** [comment]
Well we have a big parser for one ;)

The main thing is that JSX elements aren't allowed in .ts files. They'll require .tsx. So we can sidestep the issue for now and just fix .ts to handle casts properly and then figure out full JSX later. All we're really doing is implementing the grammar here: https://facebook.github.io/jsx/

**Comment by pkaminski** [comment]
I assume old-style casts aren't allowed in `.tsx` files?  If so, it sounds like there's really two separate language definitions, but I don't know how best to handle this in highlight.js since it tries to auto-detect the language used, which will be essentially impossible to do based solely on regexes and getting it wrong will screw up the highlighting.

In the meantime, I've hacked the TypeScript language definition used in Reviewable to ignore anything that looks like embedded XML.  It's not a long-term solution though.

**Comment by danquirk** [comment]
Right, in .tsx you'll use the ```as``` operator rather than <> to cast. https://github.com/Microsoft/TypeScript/pull/3201

My reviews are now beautifully colorful so thanks for unblocking it there. We'll need to figure out what to do with highlight.js as you say.

**Comment by isagalaev** [comment]
Guys, I'll try to look into it coming Tuesday.

**Comment by isagalaev** [comment]
Status update.

Since there are apparently two incompatible variants of the syntax, we could probably make it work with two separate language definitions. I couldn't put together one quickly though, need to work out a nice way of reusing the TypeScript definition to add an XML-like mode on top in TypeScript + JSX (or whatever we end up calling it).

**Comment by pkaminski** [comment]
Since TypeScript+JSX is not yet out, perhaps it's worth modifying the 'ts'
definition to remove the E4X production right now to unbreak the parser and
figure out the 'tsx' language later?

On Wed, Jul 1, 2015 at 12:52 PM, Ivan Sagalaev <notifications@github.com>
wrote:

> Status update.
>
> Since there are apparently two incompatible variants of the syntax, we
> could probably make it work with two separate language definitions. I
> couldn't put together one quickly though, need to work out a nice way of
> reusing the TypeScript definition to add an XML-like mode on top in
> TypeScript + JSX (or whatever we end up calling it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/878#issuecomment-117806352>
> .
>



-- 
  Piotr Kaminski <piotr@ideanest.com>
  "That bun is dirty.  Don't eat that bun."

**Comment by isagalaev** [comment]
@pkaminski: Indeed! e9b6c64.

**Comment by pkaminski** [comment]
Thanks!

On Wed, Jul 1, 2015 at 3:13 PM, Ivan Sagalaev <notifications@github.com>
wrote:

> @pkaminski <https://github.com/pkaminski>: Indeed! e9b6c64
> <https://github.com/isagalaev/highlight.js/commit/e9b6c64c1755e3a2aa33a1e5081c591b2db52ea6>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/878#issuecomment-117839334>
> .
>



-- 
  Piotr Kaminski <piotr@ideanest.com>
  "That bun is dirty.  Don't eat that bun."
