### ISSUE TITLE
Python inline comments break highlighting

### ISSUE THREAD

**Issue by idlesign** [isagalaev/highlight.js#885]
Hi,

The behaviour was presumably introduced in 8.1 and still out there in 8.6.

8.0:
![8.0](https://cloud.githubusercontent.com/assets/145644/8726331/00fc366c-2bf3-11e5-9a1c-35d82542720a.png)

8.1+
![8.1+](https://cloud.githubusercontent.com/assets/145644/8726349/1337e524-2bf3-11e5-926c-1d1107a7cb97.png)

**Comment by isagalaev** [comment]
The bug is not in Python's definition, it's a mis-detected language. And I should say that the fact that it used to work before was but a lucky accident: there are too few things in the snippet to get a clue from. For me it actually breaks differently: any languages with non-# comments would have a high score because it would pick up commented strings as highlightable objects.

This is a good example of the limits of language detection and I can only recommend specifying the language explicitly to overcome it.

**Comment by idlesign** [comment]
Sorry, forgot to mention that Python is enforced with `class="python"`. 
Is it somehow not a valid way of parser definition?

**Comment by isagalaev** [comment]
> Sorry, forgot to mention that Python is enforced with `class="python"`.

It should work then: http://jsfiddle.net/c5ac72fe/

Could you put up a file somewhere showing the problem?

**Comment by idlesign** [comment]
Tested it here http://pythonz.net/references/named/str.rpartition/ (now switched back to 8.0). Will try to reproduce this evening (NSK).17.07.2015, 09:49, "Ivan Sagalaev" <notifications@github.com>:
Sorry, forgot to mention that Python is enforced with class="python".


It should work then: http://jsfiddle.net/c5ac72fe/

Could you put up a file somewhere showing the problem?

—Reply to this email directly or view it on GitHub.

  
    
    
  
  

-- Игорь Стариков

**Comment by idlesign** [comment]
No need in file: the problem is in linebreaks interpretation. Old versions played well with `<br>` inside `<code>`, but not new. Yet, I wonder wether is could be considered a regression at all.

**Comment by isagalaev** [comment]
Ah! We changed handling of pre/non-pre containers at some point to use browser-native text extraction for performance. Since your code doesn't mix `<br>` and literal new-lines, I think simply calling `hljs.configure({useBR: true})` before `hljs.initHighlightingOnLoad()` should fix highlighting for you.

**Comment by idlesign** [comment]
Solved. Thank you.
Closing this.
