### ISSUE TITLE
Keywords within names should not be highlighted

### ISSUE THREAD

**Issue by battermann** [isagalaev/highlight.js#920]
<pre><code class="fsharp">module MyModule = 

    let doSomething log =
        log(sprintf "doing something" ) |&gt; ignore
        "result"
    </code></pre>

Here "do" within "doSomething" is highlighted but shouldn't be:

![image](https://cloud.githubusercontent.com/assets/3968185/9514752/11fc13c2-4c9d-11e5-9165-e927ea61234a.png)

This is my config:

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/styles/github.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

**Comment by isagalaev** [comment]
Hi!

The problem here is that the CDN build you're linking only includes a limited set of common languages, F# not among them. Consequently, it doesn't know what `class="fsharp"` means and proceeds with language detection which doesn't do any good to your snippet, of course.

Fixing it right away is fairly simple by including F# definition separately after the library:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/languages/fsharp.min.js"></script>
```

Alternatively you could download a custom build with only languages you need from https://highlightjs.org/download/.
