### ISSUE TITLE
Cannot build with node4x

### ISSUE THREAD

**Issue by mhartington** [isagalaev/highlight.js#953]
Trying to install the necessary dependencies and build but:

1) The dependencies fail to install with node4x, updating their versions to the latest fixes that
2) Updating the dependencies breaks build.js

**Comment by mhartington** [comment]
Looks like jsdom is the culprit.

**Comment by sourrust** [comment]
I froze jsdom at it's current version because the versions after were exclusively for io.js, back before node 4.0.0 was release. I'm not sure how many of the other core developers have updated to the new version but I don't have any plan to fix the dependencies officially since it is purely for development. For now, here is [a branch][4.0.0] you can use for the newer versions of node.

[4.0.0]: https://github.com/isagalaev/highlight.js/tree/node-4.0.0

**Comment by isagalaev** [comment]
> I'm not sure how many of the other core developers have updated to the new version but I don't have any plan to fix the dependencies officially since it is purely for development.

Shouldn't we move to node 4.0.0 too eventually? I don't use it for anything else other than highlight.js currently so I don't really have any preference on it apart from the general idea of staying with mainstream. What's your take on it?

**Comment by sourrust** [comment]
I've moved to version 4 awhile ago but I switch back and forth for highlightjs. It isn't too much updating because I have the branch of what needs to change. I just need to know if @Sannis is updating as well and I'll merge the branch in when I get back home.

**Comment by Sannis** [comment]
For me it is no problem to use any node version.

**Comment by isagalaev** [comment]
I only just started to wonder if @Sannis  is online at 1am but there he is :-)

Let's go ahead with this then. Thanks Jeremy!

**Comment by sourrust** [comment]
Had some trouble the dependency used for web worker testing. Luckily I found another library that worked for node 4 and Travis is all passes.

![](https://cloud.githubusercontent.com/assets/365596/10807882/1868df16-7da2-11e5-8c3a-b398d6b646e5.PNG)
