### ISSUE TITLE
Number highlighting in bash is too "greedy"

### ISSUE THREAD

**Issue by andyperlitch** [isagalaev/highlight.js#983]
First off, great library! Thanks for all the effort.
Here are just a few examples of number highlighting in bash I take issue with: 

![image](https://cloud.githubusercontent.com/assets/1390651/11153002/d7d97e1a-89ea-11e5-8396-c88873e186a6.png)

The "67" and "6" are part of alphanumeric strings that should probably not be marked as numbers.

![image](https://cloud.githubusercontent.com/assets/1390651/11153007/df5e325c-89ea-11e5-95e3-72c68269afa4.png)

In this case, the "512" seems okay because the number is surrounded by whitespace, however the 3.2.0 in `apex-3.2.0-incubating` should probably not be marked as a number.

It seems to me like some internal regex should only be matching numbers that don't have word characters or dashes next to them, e.g. `/(?<![-\w])[\d\.]+(?![-\w])/`

Thanks!
Andy

**Comment by isagalaev** [comment]
I actually have a more radical and simple idea: don't highlight numbers in Bash at all.

Since Bash is not responsible for parsing command line parameters, it's simply impossible to highlight numbers correctly. In the example above version numbers aren't semantically numbers, they're part of strings. And in something like `nice -n10` 10 actually is a number, it also can be written as `nice -n 10`.

It *may* be possible to define contexts with the actual Bash syntax, like "anything between `if` and `then`", but I don't know Bash enough to implement that.
